### PR TITLE
use network line terminator

### PR DESCRIPTION
**Pull request by stmuk**

### CODE REVIEW

**Comment by tadzik** [comment]
Is it actually necessary? Are there cases when the existing code doesn't work?

**Comment by FROGGS** [comment]
http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4 also says that CRLF is correct here.

**Comment by stmuk** [comment]
I'm not aware of cases when the existing code doesn't work.  At least two of the reports about panda not receiving projects.json were due to  ecosystem-api.p6c.org being blocked by ISP and company firewalls (probably as a side effect of the IP address hosting other content).

I'd still recommend changing the code to be more standards compliant in case an HTTP proxy requires this.

**Comment by FROGGS** [comment]
+1

**Comment by tadzik** [comment]
Alright, colour me convinced. Could someone test and merge it? I won't be able to do it in immediate future.

**Comment by stmuk** [comment]
Can someone merge this please?

**Pull request merged**
