### PR TITLE
Some modules don't seem to have a version; don't barf

### PR DESCRIPTION
**Pull request by will-crawford**
Pedantic solution (don't yield -Inf if the list ends up empty).

### CODE REVIEW

**Comment by niner** [comment]
You will need an explicit flat in there with the glr. May as well do it now since it should not hurt on nom.

**Comment by will-crawford** [comment]
Option two is definitely "copy the code from the next line" :)

**Comment by will-crawford** [comment]
Should I do that and rebase?

**Comment by will-crawford** [comment]
... wait, .max yields a scalar, surely?

**Comment by tadzik** [comment]
I surely hope so :)

I'm ready to accept it, but it's even better if it works for both nom and glr, so if you feel like getting two birds with one stone that'd be awesome :) Rebase or not, whatever you like best :)

**Comment by awwaiid** [comment]
Is this still an issue/need?

**Comment by tadzik** [comment]
It's still an issue if you go ahead and remove version from one of the entries in `projects.json`. So: potential issue.

When I tried it now I got warnings saying `Use of uninitialized value of type Any in string context`
`Any of .^name, .perl, .gist, or .say can stringify undefined things, if needed.`

I'll be happy to accept it if it doesn't do that :)

**Comment by tadzik** [comment]
With panda being discontinued, I'm closing the outstanding PRs. Thanks you for your contributions.

**Pull request closed without merging**
