### PR TITLE
add panda 'test-only' command

### PR DESCRIPTION
**Pull request by dwarring**
Another command from CPAN Minus.

I renamed the Panda `install` method to `process` - since it now only installs conditionally. Also changed options passing from positional to by-name.

### CODE REVIEW

**Comment by dwarring** [comment]
I changed this PR to not install dependencies, there's already the `install-deps` command to do that!

**Comment by FROGGS** [comment]
Why is it called `test-only` and not just `test`?

**Comment by ugexe** [comment]
fwiw this can already be accomplished with `panda look Some::Module && panda-test .`, or if you are testing a module you are already in the folder of its just `panda-test .` so you may want to mimic the functionality from those or mimic the new functionality in panda-test

**Comment by dwarring** [comment]
@FROGGS I took that from the cpanm --test-only option also happy with `test`
@ugexe - oops. thanks for pointing that out. Reinventing the wheel. I'll close off this PR and revisit.

**Pull request closed without merging**
