### PR TITLE
Add file which

### PR DESCRIPTION
**Pull request by timo**
a required dependency of Shell::Command as of late

### CODE REVIEW

**Comment by moritz** [comment]
FWIW if you add the subtree with `--squash`, you don't pull in all the commits from the upstream repo; maybe that's preferable.

**Comment by tadzik** [comment]
So now that's been covered by #304 I guess we can close this one?

**Comment by vendethiel** [comment]
> FWIW if you add the subtree with --squash, you don't pull in all the commits from the upstream repo; maybe that's preferable.

The PR itself can be squashed as well (see https://github.com/blog/2141-squash-your-commits)

**Comment by azawawi** [comment]
:+1: for closing it.

**Pull request closed without merging**
